export const LOGIN_DISPATCH = 'LOGIN_DISPATCH';
export const LOGOUT_DISPATCH = 'LOGOUT_DISPATCH';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const PROFILES_LOADING = 'PROFILES_LOADING';
export const PROFILE_LOAD = 'PROFILE_LOAD';
export const PROFILE_LOAD_ERROR = 'PROFILE_LOAD_ERROR';
export const CLEAR_PROFILES = 'CLEAR_PROFILES';